plugins {
	id 'java'
}

repositories {
	maven {
		url = 'https://repo.runelite.net'
		content {
			includeGroupByRegex("net\\.runelite.*")
		}
	}
	mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
	compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion

	testImplementation 'junit:junit:4.13.2'
	testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
}

group = 'com.osrsflavie.justpugginaround'

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release.set(11)
}

tasks.register('run', JavaExec) {
	group = 'application'
	description = "Launch RuneLite with Just Puggin' Around loaded"

	classpath = sourceSets.test.runtimeClasspath
	mainClass = 'com.osrsflavie.justpugginaround.JustPugginAroundPluginTest'

	jvmArgs '-ea'
	standardInput = System.in
}