displayName=Just Puggin' Around
author=OSRSFlavie
support=https://github.com/OSRSFlavie/Just-Puggin-Around/issues
description=Plays a tired sound after travelling a configurable distance with a follower
tags=pug,pet,follower,dog,cat,dogs,cats,pets,sound,audio,notification
version=
plugins=com.osrsflavie.justpugginaround.JustPugginAroundPlugin
build=standard