displayName=Just Puggin' Around
author=OSRSFlavie
description=Plays a tired sound after travelling a configurable distance with a follower
tags=pug,pet,follower,sound
version=
plugins=com.osrsflavie.justpugginaround.JustPugginAroundPlugin
build=standard